### ISSUE TITLE
Spawn grave in specific coordinates

### ISSUE THREAD

**Issue by Wiandono** [B1n-ry/Youre-in-grave-danger#10]
Hi, thank you for making this awesome mod!

I'm wondering if it's possible (now or maybe in the future) to configure the grave to only spawn in a specific location/coordinates?

**Comment by B1n-ry** [comment]
You mean like in a radius from a specific block? I could implement a feature like this but I would need more context to how it would work

**Comment by Wiandono** [comment]
Hi,

Thank you for the quick reply! Sorry for not giving enough context previously.

I have an idea to build something like a bonfire in Dark Souls. This structure will most likely be placed near the spawn (0, 0). The reason is that when you die without owning a bed, you will always be spawned there.

So every time the user dies, they can retrieve their item from the bonfire.

In my opinion, this can make the game easier for new players that die in a place that is hard to reach without having their equipment back first. But still give some sort of punishment for advanced players since they at least need to go back to spawn to retrieve their items.

**Comment by B1n-ry** [comment]
So you want to have a graveyard, that whenever someone die, their grave will generate there. No matter where. Is this correct?

I could implement a feature where you could add coordinates in the config that if empty, your grave will generate there, and otherwise try to generate where you died instead. Would this work or are you looking for anything else?

**Comment by Wiandono** [comment]
Yes, correct! It's pretty much like what you said.

If the users put a coordinate in the config files, the grave will always be generated around that area of the coordinate. Otherwise, it will be generated around the area where the user originally died.

**Comment by B1n-ry** [comment]
Ok I have the functionallity implemented I just need to push it to a new version. Will do this first thing in the morning hopefully (in like 8 hours). Just have to patch a little bug of sorts first.

EDIT: After these 8 hours I realized I had not implemented it because the config couldn't handle the way I wanted to handle coordinates

**Comment by Wiandono** [comment]
Thank you so much for implementing the feature! @B1n-ry ! I'll test it once it's available

**Comment by B1n-ry** [comment]
Ok I finally fixed all the issues (I hope) and updated the mod. Versions 1.1.9 and 1.2.3 will have this feature. You can have a list of blocks in a datapack. You add a file `data/yigd/custom/graveyard.json`. In there your structure should look something like:

```
{
  "coordinates": [
    {
      "x": 24,
      "y": 45,
      "z": 13
    },
    {
      "x": 64,
      "y": 70,
      "z": 11
    }
  ]
}
```

Thank you for your request! Seemed like a cool idea!

**Comment by Wiandono** [comment]
Understood! Will try this tomorrow!
