### ISSUE TITLE
Fell beneath bedrock, cant access gravestone

### ISSUE THREAD

**Issue by lordstarburner** [B1n-ry/Youre-in-grave-danger#107]
I went into creative and accidentally fell through bedrock and died in the void. This was in the regular world using the better MC modpack on my server. I keep trying to find a command or access the gravestone but it seems to be unreachable. Is there a command or way I can restore my inventory from that gravestone???

Please help..

**Comment by B1n-ry** [comment]
By executing the command `/yigd` you can see all your graves. If you are a server operator/play with cheats enabled you can select the grave you want and press a restore button. If you don't have access to cheats the button won't be there, but the meny will still be accessible. Graves should however generate above bedrock if you fall into the void (assuming that feature isn't disabled), no matter which dimension you're in. Restoring the grave will remove it from the world if it exists though, and if you are in the same world as the grave when you restore it. I hope this helps. I'll close this issue since this is already in the game, but fell free to ask any questions here anyway

**Comment by Meganium97** [comment]
I'm having this issue but with the end where it just places it above the void, but not in a realistically accessible position.
