### ISSUE TITLE
1.19.4 Crashes with Numismatic Overhaul

### ISSUE THREAD

**Issue by Cirvel** [B1n-ry/Youre-in-grave-danger#114]
**Describe the bug**
Dying while having coins from Numismatic Overhaul causes the game to crash.

**To Reproduce**
1. Have any coins inside the purse
2. Die in any way

**Expected behavior**
The game does not crash when dying in such circumstances.

**Desktop**
 - OS: [Windows]
 - Minecraft Version: [1.19.4]
 - Version: [1.6.0]

**Additional context**
The tested version for Numismatic Overhaul is 0.2.9.

**Comment by B1n-ry** [comment]
I swear this worked in my testing... I've been looking at this for a moment now and I kinda think this is more of an issue with owo lib or numismatic overhaul. I'm pretty sure I'm calling on the methods I use in an appropriate way, but I could be wrong. The issue lies within owo lib though. Or numismatic overhaul. Depends on how owo lib is supposed to work.
At least I don't think I can do much about this...

**Comment by Cirvel** [comment]
Can't blame you, the current Numismatic Overhaul mod for 1.19.4 is tagged as a beta after all, so it should be expected that there are bugs within it. I'm just gonna hold that mod off for now, I prefer not having all my stuff lost to lava or despawning.

**Comment by B1n-ry** [comment]
I created an issue on their github, and by the looks of it it's fixed in development and will be officially fixed in the next update of owo-lib. You can check out the other issue [here](https://github.com/wisp-forest/numismatic-overhaul/issues/83).
I'll close this issue once it's officially fixed

**Comment by B1n-ry** [comment]
The issue seems to be fixed in the latest release of owo-lib. Thanks for bringing this to my attention
