### ISSUE TITLE
Held Item Dissapears

### ISSUE THREAD

**Issue by Carooosa** [B1n-ry/Youre-in-grave-danger#13]
**Describe the bug**
A somewhat clear description of what the bug is.

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS]
 - Minecraft Version: [e.g. 1.16.5, 1.17.1]
 - Version: [e.g. 1.0.0, 1.0.3]

**Additional context**

**Screenshots**

**Comment by B1n-ry** [comment]
Thank you for your bug report! Would apreciate if you could apply further context, as to what held item disappears (before or after death?), minecraft version, mod version, and even perhaps screenshots of your inventory before and after. Depends on how much you feel like doing. Keep in mind that more information will help me fix the bug faster.

**Comment by B1n-ry** [comment]
I rewrote some code that I think should be connected to this issue. I'm pretty sure that this should have fixed it if there was a problem for you (it wasn't for me for some reason). Fixed in release 1.2.6
I'm closing this issue, but if you keep having it, please reopen the issue and try and provide more information of what goes wrong

**Comment by vladlore123** [comment]
I also have the same issue, but in 1.18. for example if I were to have a sword selected and die while the sword is selected, when I get back to open up the grave, the sword disappears.

**Comment by B1n-ry** [comment]
which version are you playing? released a new one a few minutes ago
