### ISSUE TITLE
Update to 1.20.1

### ISSUE THREAD

**Issue by LEclipse1001** [B1n-ry/Youre-in-grave-danger#131]
I have recently moved to 1.20.1 & it was a little disappointing when I noticed that this mod hadn't updated yet. I don't want to be that person but it is a little annoying. Whenever you could do this it would be great. Thank you in advance.

**Comment by HeraldOD** [comment]
I'm pretty sure there's already work going on to update, there's some activity on the "1.20" branch

**Comment by B1n-ry** [comment]
Yes I can clarify that a 1.20 update is planned, and in the works. It's just I've been putting time into a lot of other stuff since basically 1.19.4 released. I decided to rewrite the mod for 1.20, so that's also a reason that it's taking so long. The mod is in a playable state atm, but I feel like I want to add a few more features and such before a public release

**Comment by RWRmrfrog** [comment]
Is there any way we can build an early version of the mod for 1.20/1.20.1?

**Comment by B1n-ry** [comment]
You could join my [discord](https://discord.gg/GyrfpAVH3Q) and ask for tester role. That or building it manually from just downloading the source

**Comment by B1n-ry** [comment]
I updated the mod for 1.20 (and 1.20.1) the other day. It's still in beta, but it's released anyway, so I'll mark this issue as closed
