### ISSUE TITLE
Failed to decode: Failed to get element yigd:death_scroll missed input Fabric 1.20.1

### ISSUE THREAD

**Issue by NantaArthur123** [B1n-ry/Youre-in-grave-danger#135]
Client crashes when trying to connect to a server with grave keys enabled

[new 23.txt](https://github.com/B1n-ry/Youre-in-grave-danger/files/13539265/new.23.txt)

**Comment by B1n-ry** [comment]
I would assume the client does not have grave keys enabled in *their* config?

**Comment by NantaArthur123** [comment]
yes that is correct, we send the modpack without config folder, is it required for the client to have the same config as server?

**Comment by B1n-ry** [comment]
The config for the death scroll enables/disables the item from being registered in the game. So if the item is disabled, the client doesn't know what `yigd:death_scroll` means as it's not received information about such an item. I don't know if it's the optimal way of doing it, but it's how I've done it. So yes, the config is required to be changed both on client and server (only in the case of it being enabled/disabled). 
I'll close the issue since I currently have no plans of changing this behavior. Either ask your players to change their config or send the modpack with a config folder. Thank you for reporting this anyway, and let me know if there's anything else you'd have trouble with!
