### ISSUE TITLE
Crash with origins

### ISSUE THREAD

**Issue by Flnchie** [B1n-ry/Youre-in-grave-danger#139]
https://mclo.gs/8r43WvM

**Comment by B1n-ry** [comment]
This is due to a "quick fix" I added for origins drop rules to take effect. I'm working on a solution that will fix this issue, as well as improve the backup system by quite a lot (making it save all items, but labeling them with "drop rules", like if they were soulbound items, curse of vanishing items, or stuff like that). Will probably have to do slightly more extensive testing with this update though, and it might be a few weeks until it's ready, as I have upcoming exams and stuff. Thanks for reporting this anyway!

**Comment by Flnchie** [comment]
appreciate the response!! ill be sure to update when its out

**Comment by B1n-ry** [comment]
I've released a new version (yigd 2.0.0-beta.7) that at least in my testing the compat worked correctly in. Might be some unexpected results from translating the data file from previous versions to this one, but it shouldn't crash, and all new deaths, past update, should have drop rules applied correctly
