### ISSUE TITLE
Sinytra connector + Origins Forge incompatibility

### ISSUE THREAD

**Issue by linaraincalzando** [B1n-ry/Youre-in-grave-danger#149]
I will completely understand if you do not support this issue, I just wanted to make you aware of it and to create a log for if anyone else comes searching for an answer with the same corner case.

When using Sinytra with Forge Origins there are some odd interactions. The first initial death in the save crashes the game and then after that every time you die after you just keep your inventory.

Here is the log https://paste.atlauncher.com/view/c2804861-ad25-4a4a-8105-630cef303179

And here is the particular line I think that might be my specific issue. 

![image](https://github.com/B1n-ry/Youre-in-grave-danger/assets/99147940/51082b6e-ab54-493c-8449-c5cfb4669648)

**Comment by B1n-ry** [comment]
It seems like apoli, the library handling all origin powers, is built differently for forge. I have no idea why, although I don't know how forge or neoforge operates, so it's possible it makes sense in some way. If this issue would be fixed, it would be apoli that would have to fix it. (I believe this is the forge port repo: https://github.com/EdwinMindcraft/apoli/tree/1.20.x/forge). 
Another way to fix the issue would obviously be to use the fabric version of origins. I don't know if this would break other compatibility though, but there's a possibility it does not, since origins allow custom origins through datapacks (which I haven't looked at, but it would make sense if they were universal, meaning working for both forge and fabric). I'll keep the issue open for maybe a week, before closing it as not planned, in case you manage to actually resolve the issue

**Comment by B1n-ry** [comment]
On a second look I've found that it doesn't work because the files have moved location. 
As I highly doubt this would be changed to the "correct" file path on the forge version of apoli, since that would most certainly break quite a few forge mods, the easiest solution is to just use a grave mod built for forge.

**Comment by linaraincalzando** [comment]
That's along the lines of what I was expecting, I just consider YIGD to be the best of all gravestone mods and flagged this on your git for whenever someone else comes looking.

**Comment by B1n-ry** [comment]
Thanks! Might be of note also, that it's possible to straight up disable the origins compat in the config of YiGD (almost forgot I had that implemented lol)

**Comment by linaraincalzando** [comment]
I did not know that was an option. I will test it out. Thanks again!

**Comment by linaraincalzando** [comment]
Disabling Origins compat fixed it! Thank you so much!
