### ISSUE TITLE
Player inventories being wiped when retrieving old graves

### ISSUE THREAD

**Issue by Tempest-5ky** [B1n-ry/Youre-in-grave-danger#151]
What it says on the tin- when a player attempts to retrieve items from an old grave, their entire inventory is wiped, including worn items, and the console is spammed with the following message:
https://mclo.gs/WYPz159

Minecraft Fabric 1.20.1
YIGD v2.0.0

**Comment by B1n-ry** [comment]
When you say "old grave", what exactly do you mean by that? One that has existed for a long time, gone through a minor update, a major update, or what exactly do you mean?

**Comment by Tempest-5ky** [comment]
Apologies for being unclear! I meant it as a grave that’s been around for a
short while and that isn’t the most recent one (at least in the two times
that this has happened thus far). I haven’t updated the mod on the server
during the time that these graves have existed.

**Comment by B1n-ry** [comment]
I think I can see what has happened. I presume some mod has been added before the grave generated, and now this grave does not contain any items in an inventory container expected to be added by this other mod. I tried to make sure this error would not happen in this update, the thing is that it seemed to work sort of fine before the update, but not anymore. If this is the case I know how to fix it though. Perhaps I'll try to release an update later today, but could as well be a few days until I do so.

**Comment by Tempest-5ky** [comment]
No worries, thank you so much for your help! I’ll keep an eye out for the
update. Would it have to be applied both serverside and clientside, or
would just updating the mod on the server work?

**Comment by B1n-ry** [comment]
Updating it on the server should be sufficient, unless I make any changes to the client, which is as of now not planned. I'll let you know here when I update and in case I make changes to the client

**Comment by B1n-ry** [comment]
A few days turned into a few weeks. Part of the reason why it took the time it took is because I had my exams. I can't remember if I actually fixed the issue or not. I'm having a hard time seeing a world where I didn't, but in case I forgot, let me know.
I did change some item registration stuff in this new version, which usually means clients need to update, but in this case I actually don't know, as I'm not aware if minecraft will sync disabled blocks/items/other features. (And disabled items is what I'm using instead of conditional registration). You're welcome to try and see if it's possible, but just count on the possibility it might not work.
Thank you for reporting the issue though! If there's anything else you find, let me know!
