### ISSUE TITLE
Invisible Doors

### ISSUE THREAD

**Issue by Fyoncle** [B1n-ry/Youre-in-grave-danger#163]
![image](https://github.com/B1n-ry/Youre-in-grave-danger/assets/63975256/bf00bc1e-dc54-4bba-8bb8-80ea51e316a3)
Doors can be half invisible rarely if you die close to them, atleast thats what happened to me..

**Comment by B1n-ry** [comment]
Sorry for not commenting here sooner. The graves will place where you died, and remember what block were there before (at least this is the default behaviour, but can be changed in configs).
This will only remember the specific part of the block (in this instance, the lower part of the door).

It's a simple fix though, just telling the game "hey I just tried to place this", and it will fix itself (should work if this would happen to other blocks too, like beds)
It will be fixed in the next release of the mod. Thanks for reporting!

**Comment by Fyoncle** [comment]
Thanks so much!

**Comment by Fyoncle** [comment]
> Sorry for not commenting here sooner. The graves will place where you died, and remember what block were there before (at least this is the default behaviour, but can be changed in configs). This will only remember the specific part of the block (in this instance, the lower part of the door).
> 
> It's a simple fix though, just telling the game "hey I just tried to place this", and it will fix itself (should work if this would happen to other blocks too, like beds) It will be fixed in the next release of the mod. Thanks for reporting!

Any news for 1.20.1? ;(

**Comment by B1n-ry** [comment]
It will be in the next update. I'm working on updates past 1.20.1 that I want to get done, but it should be out within a few weeks. Currently on my summer break though, so development is slow

**Comment by Fyoncle** [comment]
> It will be in the next update. I'm working on updates past 1.20.1 that I want to get done, but it should be out within a few weeks. Currently on my summer break though, so development is slow

Thanks for fast response, was just curious ;) ❤️

**Comment by B1n-ry** [comment]
Just updated the mod on curseforge and modrinth with the fix :)

**Comment by Fyoncle** [comment]
> Just updated the mod on curseforge and modrinth with the fix :)

Thank you so much ❤️
