### ISSUE TITLE
item to teleport to last grave location

### ISSUE THREAD

**Issue by BanWolf** [B1n-ry/Youre-in-grave-danger#164]
I remember that on previous version there was an item to teleport to my last grave site, can you add something like that for 1.20.1?

https://github.com/B1n-ry/Youre-in-grave-danger/issues/18

**Comment by B1n-ry** [comment]
It is included in the mod, you just have to enable it in the config. You're looking for the Death Scroll config. Where you configure if the item should load or not you can also change what will happen when the scroll is used. If you want it to teleport you to the grave location, make sure it's set to `TELEPORT_TO_LOCATION`. I'll close the issue, but do let me know if you have more questions (or if I just misunderstood the request)

**Comment by BanWolf** [comment]
how do I craft the scroll? jei doens't show any recipe

**Comment by B1n-ry** [comment]
The scroll doesn't have a recipe by default. I removed it because it would either create an error when disabled, or be weird in JEI/REI/whatever you use. 
A previous update should have fixed it though, so I could probably add the recipe back. Otherwise you can easily create a datapack with a recipe for it though
