### ISSUE TITLE
Way to have lava not burn your stuff after opening a grave

### ISSUE THREAD

**Issue by art0007i** [B1n-ry/Youre-in-grave-danger#169]
Currently the graves store the previous state of a block they replaced. but if you for example died in lava and then opened your grave it will restore the previous state which was lava and burn you or your items.

I think that there should either be a way to disable the feature completely or add a blacklist so for example lava would not be restored when it was the previous state.

Another thing that could help, is if instead of dropping the items on the grave block, drop them at the players feet.

**Comment by B1n-ry** [comment]
Ohhh yeah that makes sense. I'll add a blacklist. You could change the drop type to be IN_INVENTORY and just change the claim priority to "player" instead of "grave". That will essentially do the same thing as dropping all the items at the player's feet, except some of the items go straight into the inventory in free slots

**Comment by B1n-ry** [comment]
I've added a new tag in the latest update `replace_grave_blacklist`, which just contains blocks that the grave will not place back
(default lava, fire, and cactus)
