### ISSUE TITLE
Storing xp in the grave

### ISSUE THREAD

**Issue by weirdchildren** [B1n-ry/Youre-in-grave-danger#179]
Hello!

These are my current config settings for exp
"expConfig": {
    "dropBehaviour": "PERCENTAGE",
    "dropPercentage": 100,
    "keepPercentage": 100
  },

I was wondering if there is way to make it so the grave stores 100% of the xp you had when you died.
At the moment when I die I already have 100% of my levels despite not yet claiming my grave.
If there isn't a way do you have any plans to add this feature in the future?

**Comment by B1n-ry** [comment]
I guess the percentage rates are a little bit weird. The `keepPercentage` is how much of the xp that would otherwise be placed in the grave, would be redirected to the player when respawning. So keeping the `keepPercentage` at 100 will make sure that xp is not placed in the grave, but kept on respawn every time. Set this to 0 to have 100% of the xp stored in the grave instead
