### ISSUE TITLE
Dying crashes game with a soundbug

### ISSUE THREAD

**Issue by bytebone** [B1n-ry/Youre-in-grave-danger#20]
**Describe the bug**
When dying, the game crashes. This seems to happen consistently, every time.

**To Reproduce**
1. have mod version 1.2.12 installed
2. die

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Minecraft Version: 1.18.1
 - Version: 1.2.12

This happens on a heavily modded fabric installation, and I haven't tested for this bug with ONLY the grave mod installed. I have some other mods installed that work with audio, namely "Dynamic Surroundings" and "Presence Footsteps". 
BUT I've tested in the same environment with 1.12.11, where the crash doesn't happen.

Crashlog is attached. Though I find the additional error message to be interesting as well:
`AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead`
`AL lib: (EE) alc_cleanup: 2 devices not closed`

[crash-2022-01-18_21.06.14-server.txt](https://github.com/B1n-ry/Youre-in-grave-danger/files/7892084/crash-2022-01-18_21.06.14-server.txt)

**Comment by B1n-ry** [comment]
Not quite sure how to read those error messages or what they mean. I can however see in the crashlog what went wrong and it's now fixed in a new update. I hope this will provide better stability.
This didn't happen to me when testing on other modpacks, but none the less it should now work on yours too. Enjoy!
