### ISSUE TITLE
Dying crashes the game

### ISSUE THREAD

**Issue by Lyohz** [B1n-ry/Youre-in-grave-danger#21]
**Describe the bug**
The game crashes on every death.

**To Reproduce**
1. Have mod version 1.2.13 installed.
2. Die.

**Desktop:**
 - OS: Windows 10
 - Minecraft Version: 1.18.1
 - Version: 1.2.13
 - Java: 17.0.2

At first I thought some other mod in the modpack was breaking things, until I tried the grave mod alone and it kept happening.
The game crashes under any death condition.
-Dying with empty inventory crashes the game immediately.
-Dying with anything in the inventory spawns the grave for a split second and crashes the game.

[crash-2022-01-20_15.25.12-server.txt](https://github.com/B1n-ry/Youre-in-grave-danger/files/7907764/crash-2022-01-20_15.25.12-server.txt)

**Comment by B1n-ry** [comment]
What mods are you using? I tested the 1.2.13 release with all of fabric 5 before updating, but I guess you must have some other mod that is not compatible. If I were to know that would help me fixing this issue. I had a similar issue the other day where dynamic surroundings or presence footsteps could have been the cause (I don't really know tbh). Are any of these mods present? (or any other mods that add sound)

**Comment by Lyohz** [comment]
It still happens with nothing else installed (other than this mod's dependencies).
Going back into the world I find no grave nor items on the ground.

The same thing also happens with other grave mods.
The only ones that don't crash are Simple Graves and Lily's Graves (these ones drop the items instead of going back straight to the inventory).

I'm already losing my mind over this.

**Comment by B1n-ry** [comment]
I have no idea what the issue might be since it is working perfectly fine for me. As of now 1.2.13 has 755 downloads, and I haven't heard this from anyone else (which I probably should have if this happens on every death). This happens with a clean modpack profile as well? How are you launching the mod by the way? Do you use the vanilla one, curseforge, multimc or anything else? I will try and help to figure out why this is happening to you, and I think it's something off with your install/environment rather than the mod itself. No matter I will still try and help you find a solution to the best of my abilities

**Comment by Lyohz** [comment]
Now I'm mad. I tried another launcher and it worked. SKLauncher betrayed me.

**Comment by B1n-ry** [comment]
Oh well piracy is not supported in fabric, and as far as I know SKLauncher is a piracy launcher. Anything non pirated should work. I don't really know what launcher you changed to, so I can't know if you actually used SKLauncher with a proper login or not. Anyway, if you did, I'm happy you got it working. Now you know why (or probably why) it happened.

**Comment by Lyohz** [comment]
I've settled on GDLauncher. Thanks a bunch for your attention.
