### ISSUE TITLE
Optifine+Optifabric incompatibility

### ISSUE THREAD

**Issue by RyanCR03** [B1n-ry/Youre-in-grave-danger#22]
https://crashy.net/E8uG0CXtDlu1B1Jk0FsA

**Comment by B1n-ry** [comment]
Please provide your entire crash log. You should ve able to just attach it (the txt file) to your github comment. Also this looks like an incompatibility. What mods are you using?

**Comment by B1n-ry** [comment]
Oh sorry, just took a second look and I realized I didn't knew how the site worked. I think I am aware of how to use it now. The crash is due to a known incompatibility with optifabric. I can see if there's something I can do, but in general I recommend using sodium and other [optifine alternatives for fabric](https://lambdaurora.dev/optifine_alternatives/)

**Comment by B1n-ry** [comment]
I've tried taking a look at it but there's no real good way of me to making my mod compatible with optifine + optifabric without breaking some stuff on the client I'm pretty sure. There's a replacement for almost every optifine feature for fabric. You can make it work with the same/better performance as you can with optifine if you take a few minutes and look up the mods with the features you're after. I hope you understand why I won't implement compatibility at my end

**Comment by B1n-ry** [comment]
Eh I actually fixed it after all. Still, I would highly recommend optifine alternatives, but now this is at least still playable with optifabric (in version 1.2.19)
