### ISSUE TITLE
doImmediateRespawn places grave weirdly in nether

### ISSUE THREAD

**Issue by Astropye** [B1n-ry/Youre-in-grave-danger#33]
I went to the Nether and fell to my death, of course, but I went back and the grave wasn't there. I died multiple times just to get back to the overworld, and each time, a grave did not spawn. I went to spectator mode to look around and there was nothing, However, I'm playing Valhelsa 1.1.0a, which includes dimension stack, so maybe that has something to do with it? I also have instant respawn on, and the grave sometimes spawns next to my bed when I die from falling - if that changes anything.

**Comment by B1n-ry** [comment]
Thank you for reporting. I'll look into the instant respawn thing, and change your grave location to where you actually died. 
About your items being lost (which I should have started with tbh), can you send me your logs? I can try to replicate this on my own but in case I can't it would help if I can see if anything was not handled by the mod

**Comment by Astropye** [comment]
I've never done this before, where do I find the logs? Should I just send the whole modpack folder?

**Comment by B1n-ry** [comment]
In the modpack folder, there is a logs folder. There you get the latest.log and send it to me. It will include everything between the last time you started the modpack and you closed it again

**Comment by Astropye** [comment]
[latest.log](https://github.com/B1n-ry/Youre-in-grave-danger/files/8217281/latest.log)
Got it

**Comment by B1n-ry** [comment]
Alright I think I found a fix for it. I managed to replicate it and the grave was placed, just not at all where it would've been. You can try the command `/yigd grave` or `/yigd moderate` to find the graves location (as long as valhelsia hasn't disabled those commands). I won't be pushing the update as soon as I've pushed bug fix updates before, as development currently is slower than it's been previously. I have a few other things I want to fit in the next update as well
Also I didn't find anything in the log that indicated you dying. (Could've been due to you restarting the game between you dying and sending the logs but it shouldn't matter as I'm pretty sure I found a fix ~~no clue how it happened in the first place though so I could be wrong~~).

Thank you for taking the time to report this though! I really appreciate when I get feedback on how I can improve things, just too bad that usually means people lose all their important items....
I'll post an update here and/or close this issue as I update the mod

**Comment by Astropye** [comment]
I appreciate all the help, I manged to find my stuff AND get back out alive - a feat in itself (for me, at least). Glad I could help out in return!

**Comment by B1n-ry** [comment]
Renamed the issue since it's kinda what happened, and since it's not actually solved I'll reopen it. If anyone else would check the open issues and not find this here as it's not in a new version yet. It's fixed, but only in dev so far

**Comment by B1n-ry** [comment]
2 months later and I can finally say I've included this in the newest update. I'm sorry it's been so long. I've just been busy with other features in the mod and other stuff in my life. Anyway I hope this will work for you! New version is available for 1.18.1 and 1.18.2 on curseforge, modrinth and github
