### ISSUE TITLE
yigd restore dupe bug

### ISSUE THREAD

**Issue by atlgeek007** [B1n-ry/Youre-in-grave-danger#39]
**Describe the bug**
On testing out "/yigd restore" as an option for certain people on the server (people who've helped pay, vips, etc), I found that it restores the grave without an issue but also does not remove the grave, leading to item duplication.

**To Reproduce**
1. Die
2. Perform "/yigd restore"
3. have all your items restored
4. find your grave still existing in world
5. right click the grave to have it restore it again, dumping your current inventory if it overflows onto the ground
6. find that you've duped everything

**Expected behavior**
The old grave disappears once restored.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.18.2
 - Version: 1.3.1

**Comment by B1n-ry** [comment]
This must be of a small error I seem to have made a while back. It should destroy the grave. It's supposed to destroy the block if it's a grave, but I seem to have accidently made it so it can only destroy the block if the block is *not* a grave. Anyhow, this should be fixed in this next version which will be out until at least this friday. I'll close the issue whenever I update

**Comment by atlgeek007** [comment]
danke schoen!

**Comment by B1n-ry** [comment]
This should now be fixed in the newest release for 1.18.1 and 1.18.2
Thanks for reporting in this issue!
