### ISSUE TITLE
[Feature Request] Graveyard based on conditions

### ISSUE THREAD

**Issue by itsdinkd** [B1n-ry/Youre-in-grave-danger#45]
There is a mod called "the graveyard" for fabric 1.18.x and basically it adds pretty awesome graveyard structures and mobs throughout overworld. 

Since this mod has the graveyard feature, I was hoping you could add some compatibility or maybe some options to allow modpack developers to have YIGD look for given structure names, in this case 'the_graveyard:medium_graveyard' or large, or small, etc. etc. and if enabled, YIGD will look for the nearest targeted structure and place the grave in said structure (medium graveyard in this example). 

The player will then be notified that there grave is in nearest [STRUCTURE NAME]

**Comment by B1n-ry** [comment]
This idea actually sounds really dope. I will have to see if there's a way I can implement this. I definetely want to. Could be a bit complicated however. I don't really know how I would go by finding a coordinate to place the grave at, or make the graves translate in a good way, but if I can, I will definetly make it happen.

**Comment by itsdinkd** [comment]
Maybe TelepathicGrunt can help ya out if they have time/you have time. wizard at terrain stuff. I imagine there might be a way to search for the structure and possibly make a rule where it replaces the Graveyard mod's own grave block that it has in said graveyards (depending on the graveyard structure, it has about 4-20 graves) :D

**Comment by B1n-ry** [comment]
Just as an update, I've now managed to get this mostly working. When you die the mod will search within a radius and replace one of the graveyard mod's graves by your own grave. If there are no graveyard graves where they are supposed to be in the graveyard, graves will generate as they normally would. I've not yet managed to make it work for the large graveyards however, since those generate differently from the other ones. 
You did suggest that the graveyard mod's grave models could be used, however I imagine this would be very hard to accomplish, as I've put quite some time in the grave renderer, trying to make that as customizable as possible. The best way would be to use a resource pack in that case, but then all grave models would change.
I'll make another comment here when I'm done

**Comment by B1n-ry** [comment]
Ok even though it felt like it that last part didn't take that long to do. The feature is complete and ready for the next update. It's a really cool suggestion, but I feel like I did it in a very insufficient way. Currently I'm cross referencing the structure files to where graves are located in them, but the only other way I can think of is to look through every single block in a graveyard for a grave and that just feels really resource heavy. 
Anyway I'll update with another comment and close the issue whenever I release the update

**Comment by itsdinkd** [comment]
> 

OH NO I love your model haha. please don't change it! I meant you could replace the actual "grave" from The_graveyard mod with your own grave as a way to help find the graveyard structure.

**Comment by itsdinkd** [comment]
> Ok even though it felt like it that last part didn't take that long to do. The feature is complete and ready for the next update. It's a really cool suggestion, but I feel like I did it in a very insufficient way. Currently I'm cross referencing the structure files to where graves are located in them, but the only other way I can think of is to look through every single block in a graveyard for a grave and that just feels really resource heavy.
Anyway I'll update with another comment and close the issue whenever I release the update

Awesome cannot wait, thank  you!

**Comment by B1n-ry** [comment]
Added in newest 1.18.2 release
