### ISSUE TITLE
Server won't shutdown when deleting the world.

### ISSUE THREAD

**Issue by xErrorAmelie** [B1n-ry/Youre-in-grave-danger#49]
**Describe the bug**
The mod won't let the server shut down.

**To Reproduce**
1. delete your world while the server is running or shutting down
2. try to shutdown the server

**Expected behavior**
It should let the server shutdown and it should not throw an index out of bounds exception. 

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 Version 25120.1010
 - Minecraft Version: 1.18.2
 - Version: 1.3.5

**Additional context**
Latest.log:
https://paste.corebot.dev/xeluyalewe.cs

**Comment by B1n-ry** [comment]
I guess I just didn't expect someone to delete the world *before* shutting down their server. Anyway I've fixed the issue now I think, as far as code goes, and will release a new version this week. I'll close the issue by then. 
Reading the error it seems something went wrong when someone died and it couldn't find all this players soulbound items. But I guess it won't matter in your case if things disappear, since you're deleting the world anyway

**Comment by B1n-ry** [comment]
Included the fix in latest 1.18.2 release
