### ISSUE TITLE
Weird Configs

### ISSUE THREAD

**Issue by Laifsyn** [B1n-ry/Youre-in-grave-danger#52]
Wrong keys? XD
![image](https://user-images.githubusercontent.com/99366187/171790479-781a61a6-4680-43aa-a0e2-9102ba280ff8.png)

**Comment by Laifsyn** [comment]
How to know what're the different death types too btw?

**Comment by B1n-ry** [comment]
Oh I guess multiline tooltips didn't work as I expected... Anyway I will fix that in next release. 

You can check the github wiki for the different death types. I try to keep it updated, but since last update I've not yet had time to update it. So some configs may not appear there, as well as the "permission api compat" names

**Comment by Laifsyn** [comment]
oh, and what's deathsight?

**Comment by B1n-ry** [comment]
Death sight is an enchantment you can put on helmets. You know how graves will have that glow when you get close to them? Death sight makes that to all graves always as long as they are in your rekder distance (pretty sure this is what it is it's a while now since I added it)

**Comment by B1n-ry** [comment]
Alright even though this was a very easy fix I waited far too long to update. Newest versions for 1.18.2 and 1.19 will no longer have configs looking like this
