### ISSUE TITLE
Grave not generated for player

### ISSUE THREAD

**Issue by fatpowaranga** [B1n-ry/Youre-in-grave-danger#54]
**Describe the bug**
Basiccally the grave doesn't generate, not even registered in the grave restore menu yet we can see they died and they have a waypoint in their xaero map as well.

**To Reproduce**
I haven't found a specific step to reproduce yet, the player had many graves work fine beforehand and after.

**Expected behavior**
I would expect the grave to generate, if no physical grave can generate

**Desktop (please complete the following information):**
 - OS: Linux (Server)
 - Minecraft Version: 1.18.2
 - Version: 1.3.5

**Additional context**
 The only thing I noted is that these deaths were in a structure (a shipwreck) and at somewhat high coordinates (3000x, -1800z, for eg). Although I tried dying many times in that area and wasn't able to trigger the same issue.

**Screenshots**

**Comment by B1n-ry** [comment]
I think this is related to #47. Here I would prefer as much information as possible. What items the player was wearing, dimension they died in (I'm guessing overworld in this case), mods present, server logs, yigd_grave_data.dat file, configs, cause of death, and so on. If you can't send all this data that's fine, but the more information I get the easier it will be for me to reproduce this, and fix it. Perhaps understand why or where the issue comes from.

**Comment by B1n-ry** [comment]
Try in the new version to change the `createGraveBeforeDeathMessage` config in the latest 1.18.2/1.19 version to true. This should hopefully fix the issue
