### ISSUE TITLE
missing config or broken

### ISSUE THREAD

**Issue by LuanrRose3400** [B1n-ry/Youre-in-grave-danger#63]
[https://prnt.sc/hy6Eo3amQZyS](url)

yigd.toml is damaged

it's asking to delete it or make your own. version 1.4.1 MC 1.19

the release version has the issue but i switched to the beta and no error message pop's so it's the clean version

**Comment by B1n-ry** [comment]
The game will run as normal. The error does appear in the previous version, but only in the logs. In the full 1.4.1 release I added the screen to notify users that customized configs would not work. If you want to fix the issue, to remove the screen from showing, I would do as the screen tells you and delete the config file. It's located in the `config` folder that's in in your minecraft folder/modpack folder, which is also the folder the `mods` folder is located. The file itself is called `yigd.toml` just as the error implies.
I'll close this issue since this is intended, but if deleting the folder won't work for some weird reason, you can re-open the issue again
