### ISSUE TITLE
players can restore / rob items infinitely?

### ISSUE THREAD

**Issue by deluxghost** [B1n-ry/Youre-in-grave-danger#68]
version 1.4.1 fabric 1.19

repro:
1. give myself restore / rob permission or set op
2. /kill
3. try /grave restore or button in the scroll
4. the grave model disappears and a message says I restored items
5. restore again, I get another copy of previous items

**Comment by B1n-ry** [comment]
Since the restore/rob functions do require OP by default, it's intended to be reusable if the grave would be unfairly robbed and then required to be restored or something like that. I just feel like that's easier than just having it only restorable once. Would you want a config like `restoresPerGrave` or something like that? Let me know if you'd like anything else. I'm not sure of your usecase but I can make a new feature that's more or less tailored for your specific usecase

**Comment by deluxghost** [comment]
might be off-topic but my use case:

- a tiny private server for friends
- uses graves to only prevent item despawn (and has nice grave model)
- doesn't need features like grave lock/unlock/restore/rob, instead, everyone is trusted and can open every grave (so we can help other players bring back items)
- players can view their graves and coordinates, OP can view all graves

Now I think what I really need first is a way to disable these features (lock/unlock/restore/rob) and related notifications, and make graves public openable.

Edit: I see I can disable some commands, now I wonder how to disable notifications (like death coordinates/grave robbed)

Back to the original issue, I feel really weird to retrieve items from "nowhere" even as an OP, I am curious what use case needs to restore items multiple times. If someone's grave is robbed and he asks OP to restore his items, now both the robber and the owner have a copy of items, so why don't we just disable rob in such a case? This sounds like shouldn't be the default setting

**Comment by B1n-ry** [comment]
Alright sorry I've not responded I've not really had the time to work on the mod for some time now, but I believe I'm back now. You're correct you can disable commands and then they should not appear in the GUI. You can also configure graves to not be unlockable. You can also disable the `tellDeathPos` config to not let people know where they died. 
I assume you did this already but you can change the rob cooldown to 0, so people can always rob other graves. There is currently not a way to disable the "your grave has been robbed" message, however I will try and implement that in the next update. 
To see your own graves you can do `/yigd grave`, or just `/yigd` which by default everyone has permission to do, but only OPs have permission to see other players graves with the command `/yigd grave [user]`. OPs also have the command `/yigd moderate` which will bring the person executing the command a list of all players who have graves.

When it comes to the restore multiple times thing, in the end it's really just a way for me to make sure people don't lose their items because of me. It's happened before I've left some bad error in the code where graves just vanish, and some mods (I know about twilight) have entities that can destroy graves (and then nothing will drop). So in the end I just want to make sure people don't lose their valuable items. I understand why this can seem weird, but I just don't want anyone to get mad all their stuff is gone, and they already used the restore but it failed or something.

Is this enough of an explanation to you? If you want you can send me your config file and I can customize it to what you've asked for if you can't find the configs for yourself. Also I may not implement my idea of the `restorePerGrave` config unless you specifically ask for it, since I don't see a valuable enough use in it (but please do tell me if you do)

I think I've answered all questions, but please let me know if I missed anything

**Comment by deluxghost** [comment]
thanks for the fantastic explaination!

yes now i think all i needs are

1. disable the rob message
2. correct gui buttons respect to permissions (already tracked in another issue)

maybe there will be other people have the same question like me, you can ask them to check this issue

**Comment by B1n-ry** [comment]
I've added a config `notifyWhenRobbed` in `GraveRobbing` you can disable to not notify people when graves are being robbed. The GUI buttons will now also respect permission api permissions, like that other issue was about. 
Let me know if there's anything else you would like to see in the mod!
