### ISSUE TITLE
Red line across the screen near the point of death

### ISSUE THREAD

**Issue by ElectricPants22** [B1n-ry/Youre-in-grave-danger#72]
Whenever i die, the grave works as properly and I can get my stuff back easily. The problem is a red line appears across my screen near where I died. I don't know if this is intended but its really annoying. Even after I pick up the grave, the red line persists. I go so far as I have to go to a new area and die there so i cant see the red line anymore.
![line ss](https://user-images.githubusercontent.com/110200086/181630765-0df75385-8ea2-40a1-a0e5-aa02ea907cdb.png)

**Comment by B1n-ry** [comment]
This is not a feature of my mod, but of the mod `FTB Chunks` I believe. Looks like that's the map mod you're using, but could be xaeros worldmap/minimap or journeymap or something else. These mods creates waypoints when and where you die, so you can more easily find back to them. I think it should be possible to remove that feature from that mod, although I'm not sure how that would work (as I did not make those mods). There probably is a config somewhere. The other thing you can do is to remove the waypoints after you pick up your grave. I think there should be some keybind for bringing up a GUI where you can add/remove waypoints. You can go through all keybinds if you press escape, click options, controls (I believe it is) and then keybinds (I might be slightly off but you'll find it).

I hope all of this will help you. I'll close the issue since well, it's not really my mod that's the culprit, but let me know if you find anything else you think could be done better or just doesn't seem to be working!
