### ISSUE TITLE
Void slot config for modded inventories

### ISSUE THREAD

**Issue by DogsTongue** [B1n-ry/Youre-in-grave-danger#74]
Not sure if this belongs in missing config or feature request, but it would be nice if there was a way to include modded inventories like trinkets in the "void slots" config. I'm using a mod that adds vanity armor slots using trinkets API and it would be nice if items in these slots weren't removed on death. If such a feature already exists, it would be nice if it was easier to discover so dumb people like me don't make posts like this thinking it isn't possible.

Thank you for your time and sorry if this is a waste of it.

**Comment by B1n-ry** [comment]
Well first off, there are no such things as dumb posts in this github. I want everyone to feel like they can send in issues/feature requests without feeling dumb. I rather get 18 really minor/already fixed issues than 1 good one. Although usually good feature requests are minor features. 
In thos case however it's not a bad feature request. It is currently not possible to configure trinket slots to be soulbound/voided. This is simply because I don't know how to make users configure that in a nice way. You see, the trinket inventory is made of a few groups with different names, that contains a few different slots with different names. In these slots there are finally a list of items, which are the ones you wear. Because of this users might have a hard time figuring out which trinket slot is what, and I have no real way of telling them that. So this is the main reason I do not have this feature available for trinkets or other mods storing items in a modded inventory. 
I feel like this would be easier explained with an image with branches for each group and slot, but if you didn't understand (and I would understand that because I'm not always good at explaining things), I just can't see a way to do the same as I have with vanilla inventory that users would understand how to use. 
A solution I guess would work for you though is in compatibility settings to add "keep all trinkets" config. Let me know what you think and I'll add it in the next update

Sorry for rumbling on, your feature request is a delicate one, since I can't quite do what I've done with configuring the vanilla inventory, but maybe I can do something. Let me know if you get any ideas

**Comment by B1n-ry** [comment]
Just updated the mod on curseforge, modrinth and github, and I've added a config in `GraveCompatConfig` called `keepAllTrinkets`. This basically makes your trinket inventory soulbound, keeping all the items when you die.

Thanks for the suggestion! I'm sorry I can't do this feature much better than this, but I hope it won't matter all too much to you. If you would however have any ideas of other features, or if you experience any bugs, let me know
