### ISSUE TITLE
Grave disappeared after being killed by the hydra on twilight forest 

### ISSUE THREAD

**Issue by Tobi016** [B1n-ry/Youre-in-grave-danger#80]
Grave disappeared after being killed by the hydra on twilight forest , the mark point was there but my grave don't.

**Comment by B1n-ry** [comment]
The hydra can destroy blocks, and twilight doesn't have block tags similar to other mods and vanilla that can stop the bosses from destroying blocks. I should probably get this fixed, but would require a change in the twilight code. Since twilight fabric uses mojmap and you're in grave danger uses yarn, when I try to fix this in code on my end, class names doesn't sync properly. Either I just don't know how to fix that or there is no way to fix that.
Anyway if you want your things back you can use `/yigd restore`

**Comment by Tobi016** [comment]
Thanks! is there a way to restore previous inventory? i got killed again trying to find my grave

**Comment by B1n-ry** [comment]
The command should act from latest grave that has not been claimed, but you can also do `/yigd grave`, which brings up a GUI, select which grave you want to restore (you probably have to check the "Show Destroyed" checkbox). Then a new GUI should open in which you first of all see if this is in fact the grave you want to restore, but also contains a few buttons on the right, assuming you have permissions to use them. One of these buttons is called "restore". Click that once and you should get your items back

**Comment by B1n-ry** [comment]
I've implemented a fix in latest versions for minecraft 1.18.2 and 1.19.2. Graves should be indestructable by any twilight boss now. I'm sorry for the long wait, just haven't felt like spending my decreased free-time on the mod lately. Now the fix is released though
