### ISSUE TITLE
Armor and held item dissapear when killed by another player

### ISSUE THREAD

**Issue by Igneo220** [B1n-ry/Youre-in-grave-danger#85]
**Describe the bug**
When a player is killed by another player, the grave will spawn, but their armor and whatever item they were holding dissapears
reloading the grave doesn't work, the items are mysteriously deleted

**To Reproduce**
1. Be me
2. Get murdered in cold blood
3. retrieve items from grave
4. Armor and held item don't come back

**Expected behavior**
was kinda hoping to have my stuff

**Desktop (please complete the following information):**
1.19, A whole lot of mods, but i doubt they would affect this. RelicEx is the only one i think that could.

**Comment by B1n-ry** [comment]
These items didn't have curse of vanishing did they? Because that's the only time this would happen intentionally. Personally I can't reproduce this issue, not only because step 1 is literally impossible for me lol, but also, yeah... it doesn't happen to me. Does it happen every time or was this just a one time thing?
Sorry to bother you with questions, but unfortunately I can't do much about this at the moment without additional information

**Comment by Igneo220** [comment]
Don't worry it's just the support process lol, but yeah, it's happened multiple times. At first, we thought it was a fluke but after it happened a second time we knew something was up. None of the items had curse of vanishing. My only idea is that it might have to do with some sort of feature messing with what happens with grave robbing, whatever that means past using another player's grave.

**Comment by B1n-ry** [comment]
When robbing a grave the exact same function is used as when claiming your own grave. Only noticable difference is that which inventory (grave or player inventory) should be prioritized. ~~This is configurable client side but shouldn't affect this~~.
So I don't think it has anything to do with robbing the grave. I think it's something happening when dying to how the items are stored. The only thing is that by the code I've made, all users should have disappearing items every time they die, or if the items match the slot they're in or enchantment. Everything that can destroy items on death is disabled by default though (except curse of vanishing). 
So information that would be good for me to know would be:
1. What items are disappearing exactly? What are they called and from what mod? What combinations? Same items every time?
2. Are you using a publicly available modpack, or using a private one? Is it possible to distribute it to me somehow?
3. Are you playing with origins or something similar, giving players special effects of sorts, and if so which effects and what mod?
4. How do you die? Killed by another player? Killed by a mob? Falling to death? Kill command?

A lot of questions and you don't have to reply to all of them, but the more information you supply the easier it is for me to pinpoint to what is wrong. Perhaps fix it or point towards who's doing something bad.
If you find answering any questions annoying, just let me know so I know if I should wait for a reply or not.
Also sorry for not replying sooner, I've had a busy weekend

**Comment by Igneo220** [comment]
All items that were held and in armor/trinket slots. Specifically it was a chest plate and helmet from relicex, and pants and boots from mc dungeons armor, and the set of blue wizard armor from mc dungeons armor. A netherite enchanted sword, (I'm unsure but sharp V, unbreaking III, and looting III I think) and another sword that I can't remember any details about. None of the armors were enchanted except for the relics set, which I'm pretty sure had mending.

Private modpack, I can get it to you but we recently had an update to use charm(they have a recovery totem that doesn't do this) while we wait for this mod to be fixed, since we like the "return to previous slots" feature that charm doesn't have. I also think it looks nicer (your mod is very clean)

We are using origins now, but not when the issue was made. I cannot think of any mods that may affect what happens to a player when they die, besides maybe playerex, since we lose all our levels when we die.

Killed by another player via sword. Both times. It was a simple netherite sword with sharpness V, mending, and unbreaking III named Heathen Slayer. Every death not cause by a player has had no issues.

**Comment by ProjectKaos** [comment]
Just had this happen, brother had RelicEx gear and lost all his armor from that mod, some trinkets from another mod, some MC Dungeon Armor mod gear, and lost all his Vanilla tools

**Comment by B1n-ry** [comment]
Hmm I'm noticing a theme with the relicx armor. But yeah I would appreciate getting a modpack profile to test on. If you're using curseforge launcher, you can choose "upload profile" or something, which creates a zip file with a certain format that I can easily use to get on my client. 
You should hopefully be able to attach the zip in a reply. If you have some other way of sending me the modpack I don't think I would mind. 
I can myself replace the charm mod with my grave mod, so don't worry about that.

**Comment by astalous** [comment]
Just had this happen to me as well but not from another player. Running better minecraft (fabric) mod pack from curse forge. Died on a undead ship and got everything back except armor and what was in my hot Bar. Fully enchanted netherite armor set, sword, pickaxe, bow etc. All with mending. Huge bummer as it's not my server and I can't revert to backup. The same with OP how it doesn't even show up in the gravestone info. Just all disappeared. Figured I'd comment to help fix issue.

**Comment by Igneo220** [comment]
Well there was no relicex armor in the first time it happened, and the most recent account didn't have relicex or mc dungeons armor. I hope you don't mind me (sorta) plugging myself here, but the zip folder is in my discord server, in the tutorial chat, under mods installation here:

https://discord.gg/4k2J9mjX

**Comment by B1n-ry** [comment]
Alright then I'll try to do some more extensive testing with the better minecraft modpack for now. I *think* I have about enough information now. I might use your custom modpack if better minecraft doesn't work out. Don't worry about (sorta) plugging yourself. I don't really care unless it's a scam or something like that, so you're good.
Thanks to all of you for reporting in and providing more information. I'll update ya'll when the issue is fixed, and then release a new update

**Comment by Igneo220** [comment]
Alright thanks lol, lmk if there are any developments

**Comment by B1n-ry** [comment]
I found that when using twilight's "charm of keeping", your inventory will be deleted when dying in survival mode. I think this is on twilight's part, but did anyone of you perhaps wear that when dying?

**Comment by Igneo220** [comment]
I find it unlikely because

A. One of the people that died probably didn't have it, since they not only haven't explored twilight forest at all, but that specific bug was already discovered. The other person also probably didn't have it, since they were the one that discovered it.

B. The rest of the inventory was entirely in-tact. Only the armor and held item dissapeared

**Comment by astalous** [comment]
I actually did have one equipped. The level 2 one I believe (silver).

**Comment by astalous** [comment]
"Level 2 (silver) charm of keeping keeps armor and full hotbar upon respawn" my issue seems to be leaning towards the charm of keeping bugging out and not gravestone.

**Comment by B1n-ry** [comment]
Yeah looks like it. Thanks anyway for the information. I'm moving on to testing the custom modpack in that case

**Comment by B1n-ry** [comment]
I've been looking into this for a few days, and it looks more and more like it's just the twilight keeping belt/charm. I would guess some people who found out this happened for the level 3 one didn't think it would happen at level 1 and 2? The only times in the code I have mentioned held item is when retrieving graves, and this is only if you have configured the mod to require certain items to loot graves (key or a shovel).
And as far as I know this issue is completely on twilight forest's side, as I can reproduce it without my mod even being installed.
I appreciate all of you taking time to report this, and providing all this info. I did test everything as close to the the information I received as possible, but if you still think I'm wrong, you're welcome to tell me so

**Comment by Zarepheth** [comment]
Just chiming in because I was finally killed in my single player game today, and have suffered numerous deaths since then (perhaps because I lost all my armor and items in my primary and off hands - thus losing the enchantments on them?)

Following the theme of the above, using "Better MC [FABRIC]" modpack , customizing it with many additional mods (via Curse Forge Overwolf client). I may have had Twilight Forest's Charm of Keeping on me. I notice that some items following me when I die - to my knowledge they don't have any enchantments for that purpose.

Items lost: Moissenite Armor, Shield, and tool (all from More Gems, or its integration with Basic Shields). Enchantments on the items varied, but kept getting less as I played and kept dying. The tool varied, sometimes a sword, sometimes a paxel (depending upon what was in my primary hand).

I'll review my inventory and see if I have the Twilight Forest Charm of Keeping on me.

**Comment by Zarepheth** [comment]
Update - Despite multiple deaths, I still had two charms of keeping on me, in a trinket slot, when checked.

**Comment by B1n-ry** [comment]
I've been away for a while now, but I managed to test twilight forest after they updated, and they fixed their issue. This should be stable now. If anyone would happen to still have this issue, even with latest twilight forest build (or without it), let me know, and I'll take yet another look at it. But for now I can't think of any reason this has happened except for the twilight charms of keeping
