### ISSUE TITLE
Item to TP to grave on death

### ISSUE THREAD

**Issue by k2helix** [B1n-ry/Youre-in-grave-danger#99]
**Is your feature request related to a problem or do you just have an idea that fit the theme of the mod? Please describe.**
Currently the only way to get your items back when you die is to go where you died and restore the grave, but this is not practical if you died 5000 blocks away. 

**Describe the solution you'd like**
The idea would be to do something like what Corail Tombstone for Forge does: add an item that allows you to teleport to your grave.

**Describe alternatives you've considered**
What Corail Tombstone does is giving you a key when you die and if you put an ender pearl with the key, you can use the key to teleport to your grave. Something similar could be done, and obviously it should not be free, requiring some kind of item or even specifying a chance of obtaining it without any cost.

**Comment by B1n-ry** [comment]
You can configure the mod to using death scrolls, which can be used to go back to where you died, by setting the config `scrollType` to `SCROLL_OF_RETURN` instead of `DISABLED` which its at by default. That will cause the scroll of return item to be registered when you restart the game, which can either be received when respawning, or by crafting. You can also enable grave keys, and with a datapack define a new recipe for the scroll to require a grave key and an ender pearl if you so wish. 
Do keep in mind that scrolls crafted will always only point towards your latest grave. If you make the recipe require a key it can use any key, but still the scroll will only point towards your (the person who makes the craft) latest grave.

It's could be possible (I don't know because I haven't tested) to make it work with some other mod like kubejs or nbtcrafting, to copy some nbt traits from one item to another when crafting. Then you would be able to read from the key which grave the scroll would be meant for.
I'm sorry if this is too complicated of an solution. I'd be happy to help with anything.
Let me know if there's something else you need help with!

**Comment by k2helix** [comment]
I didn't know about the existence of scrolls! Thanks for all the info.

~~So if I enable that scroll, it'll be given on respawn or just can be crafted?~~

If you want my feedback, it would be a great idea to add more scrolls with functions such as going back home or sending a tp request to another player. It would make the mod even more unique!

Edit: I've just seen the config and checked that there is an option to enable the scroll when respawning. If I do not enable it, what is the recipe of the scroll?

**Comment by B1n-ry** [comment]
The recipe is as follows: 
candle, phantom membrane, candle
ender pearl, ender eye, ender pearl
amethyst shard, crying obsidian, amethyst shard

As I mentioned before you can change the recipe with a datapack (or use mods like kubejs I think)

Your other ideas seems interesting, however I don't see them really fitting into the style of the mod. YIGD focuses on when you die and what happens then. A big part of this is the graves themselves. Your suggestions I would expect in some utility mod focusing more on servers (like mods that adds commands for this, but with items), or maybe even a magic mod. 
I'm sorry but I want to keep this mod in its own scope. Maybe I'll add something like this to some other mod in the future
